<?xml version="1.0" encoding="utf-8"?><Database Name="SimpleDatabase" Class="SampleTableDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localdb)\ProjectsV13;Initial Catalog=SimpleDatabase;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SimpleDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SampleTable" Member="SampleTables">
    <Type Name="SampleTable">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>